use crate::amino_acid::AminoAcid;

/// Per-residue physical/chemical data used by downstream layers.
///
/// Sources: average residue mass (IUPAC), Kyte–Doolittle hydropathy,
/// Zamyatnin side-chain volume, Chou–Fasman α/β propensities, side-chain
/// pKa from Lehninger. H-bond donor/acceptor counts are simplified
/// side-chain totals (heavy-atom donors/acceptors at neutral pH).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct AminoAcidProperties {
    /// Average residue mass in Daltons (free AA mass minus one water).
    pub residue_mass_da: f64,
    /// Kyte–Doolittle hydropathy. Positive = hydrophobic.
    pub hydropathy: f64,
    /// Side-chain volume in Å³ (Zamyatnin 1972).
    pub sidechain_volume_a3: f64,
    /// Side-chain pKa, or `None` if non-ionizable under physiological conditions.
    pub sidechain_pka: Option<f64>,
    /// α-helix propensity (Chou–Fasman P_α). >1 favorable.
    pub helix_propensity: f64,
    /// β-sheet propensity (Chou–Fasman P_β). >1 favorable.
    pub sheet_propensity: f64,
    /// Side-chain heavy-atom hydrogen-bond donors at pH ~7.
    pub hbond_donors: u8,
    /// Side-chain heavy-atom hydrogen-bond acceptors at pH ~7.
    pub hbond_acceptors: u8,
    /// Net side-chain charge at pH ~7 (in units of e).
    pub net_charge: f64,
}

impl AminoAcid {
    pub const fn properties(self) -> AminoAcidProperties {
        match self {
            AminoAcid::Ala => AminoAcidProperties {
                residue_mass_da: 71.0788,
                hydropathy: 1.8,
                sidechain_volume_a3: 88.6,
                sidechain_pka: None,
                helix_propensity: 1.42,
                sheet_propensity: 0.83,
                hbond_donors: 0,
                hbond_acceptors: 0,
                net_charge: 0.0,
            },
            AminoAcid::Arg => AminoAcidProperties {
                residue_mass_da: 156.1875,
                hydropathy: -4.5,
                sidechain_volume_a3: 173.4,
                sidechain_pka: Some(12.48),
                helix_propensity: 0.98,
                sheet_propensity: 0.93,
                hbond_donors: 5,
                hbond_acceptors: 0,
                net_charge: 1.0,
            },
            AminoAcid::Asn => AminoAcidProperties {
                residue_mass_da: 114.1038,
                hydropathy: -3.5,
                sidechain_volume_a3: 114.1,
                sidechain_pka: None,
                helix_propensity: 0.67,
                sheet_propensity: 0.89,
                hbond_donors: 2,
                hbond_acceptors: 2,
                net_charge: 0.0,
            },
            AminoAcid::Asp => AminoAcidProperties {
                residue_mass_da: 115.0886,
                hydropathy: -3.5,
                sidechain_volume_a3: 111.1,
                sidechain_pka: Some(3.65),
                helix_propensity: 1.01,
                sheet_propensity: 0.54,
                hbond_donors: 0,
                hbond_acceptors: 4,
                net_charge: -1.0,
            },
            AminoAcid::Cys => AminoAcidProperties {
                residue_mass_da: 103.1388,
                hydropathy: 2.5,
                sidechain_volume_a3: 108.5,
                sidechain_pka: Some(8.33),
                helix_propensity: 0.70,
                sheet_propensity: 1.19,
                hbond_donors: 1,
                hbond_acceptors: 0,
                net_charge: 0.0,
            },
            AminoAcid::Gln => AminoAcidProperties {
                residue_mass_da: 128.1307,
                hydropathy: -3.5,
                sidechain_volume_a3: 143.8,
                sidechain_pka: None,
                helix_propensity: 1.11,
                sheet_propensity: 1.10,
                hbond_donors: 2,
                hbond_acceptors: 2,
                net_charge: 0.0,
            },
            AminoAcid::Glu => AminoAcidProperties {
                residue_mass_da: 129.1155,
                hydropathy: -3.5,
                sidechain_volume_a3: 138.4,
                sidechain_pka: Some(4.25),
                helix_propensity: 1.51,
                sheet_propensity: 0.37,
                hbond_donors: 0,
                hbond_acceptors: 4,
                net_charge: -1.0,
            },
            AminoAcid::Gly => AminoAcidProperties {
                residue_mass_da: 57.0519,
                hydropathy: -0.4,
                sidechain_volume_a3: 60.1,
                sidechain_pka: None,
                helix_propensity: 0.57,
                sheet_propensity: 0.75,
                hbond_donors: 0,
                hbond_acceptors: 0,
                net_charge: 0.0,
            },
            AminoAcid::His => AminoAcidProperties {
                residue_mass_da: 137.1411,
                hydropathy: -3.2,
                sidechain_volume_a3: 153.2,
                sidechain_pka: Some(6.00),
                helix_propensity: 1.00,
                sheet_propensity: 0.87,
                hbond_donors: 1,
                hbond_acceptors: 1,
                net_charge: 0.1, // mostly neutral at pH 7, partial protonation
            },
            AminoAcid::Ile => AminoAcidProperties {
                residue_mass_da: 113.1594,
                hydropathy: 4.5,
                sidechain_volume_a3: 166.7,
                sidechain_pka: None,
                helix_propensity: 1.08,
                sheet_propensity: 1.60,
                hbond_donors: 0,
                hbond_acceptors: 0,
                net_charge: 0.0,
            },
            AminoAcid::Leu => AminoAcidProperties {
                residue_mass_da: 113.1594,
                hydropathy: 3.8,
                sidechain_volume_a3: 166.7,
                sidechain_pka: None,
                helix_propensity: 1.21,
                sheet_propensity: 1.30,
                hbond_donors: 0,
                hbond_acceptors: 0,
                net_charge: 0.0,
            },
            AminoAcid::Lys => AminoAcidProperties {
                residue_mass_da: 128.1741,
                hydropathy: -3.9,
                sidechain_volume_a3: 168.6,
                sidechain_pka: Some(10.53),
                helix_propensity: 1.16,
                sheet_propensity: 0.74,
                hbond_donors: 3,
                hbond_acceptors: 0,
                net_charge: 1.0,
            },
            AminoAcid::Met => AminoAcidProperties {
                residue_mass_da: 131.1926,
                hydropathy: 1.9,
                sidechain_volume_a3: 162.9,
                sidechain_pka: None,
                helix_propensity: 1.45,
                sheet_propensity: 1.05,
                hbond_donors: 0,
                hbond_acceptors: 0,
                net_charge: 0.0,
            },
            AminoAcid::Phe => AminoAcidProperties {
                residue_mass_da: 147.1766,
                hydropathy: 2.8,
                sidechain_volume_a3: 189.9,
                sidechain_pka: None,
                helix_propensity: 1.13,
                sheet_propensity: 1.38,
                hbond_donors: 0,
                hbond_acceptors: 0,
                net_charge: 0.0,
            },
            AminoAcid::Pro => AminoAcidProperties {
                residue_mass_da: 97.1167,
                hydropathy: -1.6,
                sidechain_volume_a3: 112.7,
                sidechain_pka: None,
                helix_propensity: 0.57,
                sheet_propensity: 0.55,
                hbond_donors: 0,
                hbond_acceptors: 0,
                net_charge: 0.0,
            },
            AminoAcid::Ser => AminoAcidProperties {
                residue_mass_da: 87.0782,
                hydropathy: -0.8,
                sidechain_volume_a3: 89.0,
                sidechain_pka: None,
                helix_propensity: 0.77,
                sheet_propensity: 0.75,
                hbond_donors: 1,
                hbond_acceptors: 2,
                net_charge: 0.0,
            },
            AminoAcid::Thr => AminoAcidProperties {
                residue_mass_da: 101.1051,
                hydropathy: -0.7,
                sidechain_volume_a3: 116.1,
                sidechain_pka: None,
                helix_propensity: 0.83,
                sheet_propensity: 1.19,
                hbond_donors: 1,
                hbond_acceptors: 2,
                net_charge: 0.0,
            },
            AminoAcid::Trp => AminoAcidProperties {
                residue_mass_da: 186.2132,
                hydropathy: -0.9,
                sidechain_volume_a3: 227.8,
                sidechain_pka: None,
                helix_propensity: 1.08,
                sheet_propensity: 1.37,
                hbond_donors: 1,
                hbond_acceptors: 0,
                net_charge: 0.0,
            },
            AminoAcid::Tyr => AminoAcidProperties {
                residue_mass_da: 163.1760,
                hydropathy: -1.3,
                sidechain_volume_a3: 193.6,
                sidechain_pka: Some(10.07),
                helix_propensity: 0.69,
                sheet_propensity: 1.47,
                hbond_donors: 1,
                hbond_acceptors: 2,
                net_charge: 0.0,
            },
            AminoAcid::Val => AminoAcidProperties {
                residue_mass_da: 99.1326,
                hydropathy: 4.2,
                sidechain_volume_a3: 140.0,
                sidechain_pka: None,
                helix_propensity: 1.06,
                sheet_propensity: 1.70,
                hbond_donors: 0,
                hbond_acceptors: 0,
                net_charge: 0.0,
            },
        }
    }
}
