//! PDB ATOM-record writer.
//!
//! Follows the column-exact PDB v3.3 specification (the relevant fields are
//! ATOM serial number 7-11, atom name 13-16, residue name 18-20, chain ID 22,
//! residue number 23-26, x/y/z 31-54 each as 8.3 floats, occupancy 55-60,
//! temperature factor 61-66, element symbol 77-78). We emit a single chain
//! "A", occupancy 1.00, temperature factor 0.00, no alternate locations.
//!
//! Multi-MODEL trajectories: [`write_pdb_trajectory`] takes any iterator
//! of structures and writes a `MODEL n` / `ENDMDL` block for each. The
//! single-frame [`write_pdb`] writes a plain PDB without MODEL records so
//! older tools that don't expect the wrapper keep working.

use std::io::{self, Write};

use geom::Structure;

/// Write a single-model PDB. No `MODEL` / `ENDMDL` wrappers.
pub fn write_pdb<W: Write>(writer: &mut W, structure: &Structure, title: &str) -> io::Result<()> {
    write_header(writer, title)?;
    write_atoms_and_ter(writer, structure, 1)?;
    writeln!(writer, "END")?;
    Ok(())
}

/// Write a trajectory PDB containing one `MODEL` block per structure.
///
/// Atoms in each model use the same residue identities — only positions
/// differ. The caller is responsible for passing structurally-identical
/// snapshots (the trajectory writer doesn't verify).
pub fn write_pdb_trajectory<'a, W, I>(
    writer: &mut W,
    title: &str,
    frames: I,
) -> io::Result<()>
where
    W: Write,
    I: IntoIterator<Item = &'a Structure>,
{
    write_header(writer, title)?;
    let mut wrote_any = false;
    for (idx, frame) in frames.into_iter().enumerate() {
        writeln!(writer, "MODEL     {:>4}", idx + 1)?;
        write_atoms_and_ter(writer, frame, 1)?;
        writeln!(writer, "ENDMDL")?;
        wrote_any = true;
    }
    if !wrote_any {
        // Mirror the single-frame writer's habit of producing a valid
        // (if empty) file rather than silently writing nothing.
    }
    writeln!(writer, "END")?;
    Ok(())
}

fn write_header<W: Write>(writer: &mut W, title: &str) -> io::Result<()> {
    writeln!(
        writer,
        "REMARK   1 Generated by origami (experimental physics-based folder)"
    )?;
    if !title.is_empty() {
        writeln!(writer, "REMARK   2 Title: {}", title)?;
    }
    Ok(())
}

fn write_atoms_and_ter<W: Write>(
    writer: &mut W,
    structure: &Structure,
    starting_serial: u32,
) -> io::Result<()> {
    let mut serial = starting_serial;
    for (res_idx, residue) in structure.residues.iter().enumerate() {
        let res_seq = (res_idx + 1) as u32;
        let res_name = residue.aa.three_letter().to_uppercase();
        for atom in &residue.atoms {
            write_atom(
                writer,
                serial,
                atom.name,
                &res_name,
                'A',
                res_seq,
                atom.position.x,
                atom.position.y,
                atom.position.z,
                element_symbol(atom.element),
            )?;
            serial += 1;
        }
    }
    if let Some(last) = structure.residues.last() {
        let res_seq = structure.residues.len() as u32;
        let res_name = last.aa.three_letter().to_uppercase();
        writeln!(
            writer,
            "TER   {:>5}      {:>3} A{:>4}",
            serial, res_name, res_seq
        )?;
    }
    Ok(())
}

fn element_symbol(e: chem::Element) -> char {
    e.symbol()
}

#[allow(clippy::too_many_arguments)]
fn write_atom<W: Write>(
    writer: &mut W,
    serial: u32,
    atom_name: &str,
    res_name: &str,
    chain: char,
    res_seq: u32,
    x: f64,
    y: f64,
    z: f64,
    element: char,
) -> io::Result<()> {
    let formatted_name = format_atom_name(atom_name, element);
    writeln!(
        writer,
        "ATOM  {serial:>5} {name:<4} {res:>3} {chain}{res_seq:>4}    {x:>8.3}{y:>8.3}{z:>8.3}  1.00  0.00          {elem:>2}",
        serial = serial,
        name = formatted_name,
        res = res_name,
        chain = chain,
        res_seq = res_seq,
        x = x,
        y = y,
        z = z,
        elem = element,
    )
}

/// PDB atom names occupy columns 13-16 (4 chars).
/// 4-character names fill the field. Shorter names get a leading space so
/// that the element letter sits in column 14 (e.g. " N  ", " CA ", " CB ",
/// "HA2 ", "HB1 ", " HG13").
fn format_atom_name(name: &str, element: char) -> String {
    if name.len() == 4 {
        // Already fills the 4-column field.
        name.to_owned()
    } else if name.starts_with(element) {
        // 1-3 chars; pad with leading space to right-align element.
        format!(" {:<3}", name)
    } else {
        // Atom name doesn't start with element symbol — left-pad anyway.
        format!(" {:<3}", name)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use ::chem::AminoAcid;
    use geom::build_extended_chain;

    #[test]
    fn writes_valid_alanine_pdb() {
        let s = build_extended_chain(&[AminoAcid::Ala]).unwrap();
        let mut buf = Vec::new();
        write_pdb(&mut buf, &s, "single Ala test").unwrap();
        let text = String::from_utf8(buf).unwrap();
        assert!(text.starts_with("REMARK"));
        assert!(text.contains("ATOM"));
        assert!(text.contains("ALA"));
        assert!(text.ends_with("END\n"));
        // 10 ATOM lines (Ala = N, CA, C, O, H, HA, CB, HB1, HB2, HB3).
        let atom_lines = text.lines().filter(|l| l.starts_with("ATOM")).count();
        assert_eq!(atom_lines, 10);
    }

    #[test]
    fn atom_columns_are_correctly_aligned() {
        // PDB columns are 1-indexed. Column 1 is the first character.
        // Verify a few ATOM lines have the right widths.
        let s = build_extended_chain(&[AminoAcid::Gly]).unwrap();
        let mut buf = Vec::new();
        write_pdb(&mut buf, &s, "").unwrap();
        let text = String::from_utf8(buf).unwrap();
        let first_atom = text.lines().find(|l| l.starts_with("ATOM")).unwrap();
        // Standard PDB ATOM record is 80 columns. We don't pad to 80 but the
        // record up through the element field should be intact.
        assert_eq!(&first_atom[0..6], "ATOM  ");
        assert_eq!(&first_atom[12..16], " N  ");
        assert_eq!(&first_atom[17..20], "GLY");
        assert_eq!(&first_atom[21..22], "A");
    }

    #[test]
    fn trajectory_writes_one_model_per_frame() {
        let s = build_extended_chain(&[AminoAcid::Ala, AminoAcid::Gly]).unwrap();
        let frames = [s.clone(), s.clone(), s.clone()];
        let mut buf = Vec::new();
        write_pdb_trajectory(&mut buf, "traj test", frames.iter()).unwrap();
        let text = String::from_utf8(buf).unwrap();
        let model_lines = text.lines().filter(|l| l.starts_with("MODEL")).count();
        let endmdl_lines = text.lines().filter(|l| l.starts_with("ENDMDL")).count();
        assert_eq!(model_lines, 3);
        assert_eq!(endmdl_lines, 3);
        assert!(text.ends_with("END\n"));
    }
}
